version: "3.9"

services:
  backend:
    image: hehej/sfc-backend:latest

  frontend:
    image: hehej/sfc-frontend:latest
    environment:
      - BACKEND_DNS=backend
      - BACKEND_PORT=9000
    ports:
      - "8080:8080"
    depends_on:
      - backend
    pull_policy: always
