name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches-ignore: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.16.x'

      - name: Build (frontend)
        working-directory: frontend
        run: go build ./...

      - name: Test (frontend)
        working-directory: frontend
        run: go test -v ./...
